CREATE TABLE [FRIEND_LIST](
	[strUserID] [varchar](21) NOT NULL,
	[strFriend1] [varchar](21) NULL,
	[strFriend2] [varchar](21) NULL,
	[strFriend3] [varchar](21) NULL,
	[strFriend4] [varchar](21) NULL,
	[strFriend5] [varchar](21) NULL,
	[strFriend6] [varchar](21) NULL,
	[strFriend7] [varchar](21) NULL,
	[strFriend8] [varchar](21) NULL,
	[strFriend9] [varchar](21) NULL,
	[strFriend10] [varchar](21) NULL,
	[strFriend11] [varchar](21) NULL,
	[strFriend12] [varchar](21) NULL,
	[strFriend13] [varchar](21) NULL,
	[strFriend14] [varchar](21) NULL,
	[strFriend15] [varchar](21) NULL,
	[strFriend16] [varchar](21) NULL,
	[strFriend17] [varchar](21) NULL,
	[strFriend18] [varchar](21) NULL,
	[strFriend19] [varchar](21) NULL,
	[strFriend20] [varchar](21) NULL,
	[strFriend21] [varchar](21) NULL,
	[strFriend22] [varchar](21) NULL,
	[strFriend23] [varchar](21) NULL,
	[strFriend24] [varchar](21) NULL
)
