CREATE TABLE [KNIGHTS](
	[IDNum] [smallint] NOT NULL,
	[Flag] [tinyint] NOT NULL DEFAULT(1),
	[Nation] [tinyint] NOT NULL,
	[Ranking] [tinyint] NOT NULL DEFAULT(0),
	[IDName] [varchar](21) NOT NULL,
	[Members] [smallint] NOT NULL DEFAULT(1),
	[Chief] [varchar](21) NOT NULL,
	[ViceChief_1] [varchar](21) NULL,
	[ViceChief_2] [varchar](21) NULL,
	[ViceChief_3] [varchar](21) NULL,
	[strEnemyName] [varchar](21) NULL,
	[byOldWarResult] [tinyint] NOT NULL DEFAULT(0),
	[nWarEnemyID] [int] NOT NULL DEFAULT(0),
	[nVictory] [int] NOT NULL DEFAULT(0),
	[nLose] [int] NULL DEFAULT(0),
	[Gold] [bigint] NOT NULL DEFAULT(0),
	[Domination] [smallint] NOT NULL DEFAULT(0),
	[Points] [int] NULL DEFAULT(0),
	[CreateTime] [smalldatetime] NOT NULL DEFAULT(GETUTCDATE()),
	[sMarkVersion] [smallint] NOT NULL DEFAULT(0),
	[sMarkLen] [smallint] NOT NULL DEFAULT(0),
	[Mark] [image] NULL,
	[bySiegeFlag] [tinyint] NOT NULL DEFAULT(0),
	[sAllianceKnights] [smallint] NOT NULL DEFAULT(0),
	[sCape] [smallint] NOT NULL DEFAULT(0),
	[bCapeR] [tinyint] NOT NULL DEFAULT(0),
	[bCapeG] [tinyint] NOT NULL DEFAULT(0),
	[bCapeB] [tinyint] NOT NULL DEFAULT(0),
	[ClanPointFund] [int] NOT NULL DEFAULT(0)
)