CREATE TABLE [MAGIC_TYPE4](
	[iNum] [int] NOT NULL,
	[BuffType] [tinyint] NOT NULL,
	[Radius] [tinyint] NOT NULL DEFAULT(0),
	[Duration] [smallint] NOT NULL DEFAULT(0),
	[AttackSpeed] [tinyint] NOT NULL DEFAULT(0),
	[Speed] [tinyint] NOT NULL DEFAULT(0),
	[AC] [smallint] NOT NULL DEFAULT(0),
	[ACPct] [smallint] NOT NULL DEFAULT(0),
	[Attack] [tinyint] NOT NULL DEFAULT(0),
	[MagicAttack] [tinyint] NOT NULL DEFAULT(0),
	[MaxHP] [smallint] NOT NULL DEFAULT(0),
	[MaxHPPct] [smallint] NOT NULL DEFAULT(0),
	[MaxMP] [smallint] NOT NULL DEFAULT(0),
	[MaxMPPct] [smallint] NOT NULL DEFAULT(0),
	[HitRate] [tinyint] NOT NULL DEFAULT(0),
	[AvoidRate] [smallint] NOT NULL DEFAULT(0),
	[Str] [smallint] NOT NULL DEFAULT(0),
	[Sta] [smallint] NOT NULL DEFAULT(0),
	[Dex] [smallint] NOT NULL DEFAULT(0),
	[Intel] [smallint] NOT NULL DEFAULT(0),
	[Cha] [smallint] NOT NULL DEFAULT(0),
	[FireR] [tinyint] NOT NULL DEFAULT(0),
	[ColdR] [tinyint] NOT NULL DEFAULT(0),
	[LightningR] [tinyint] NOT NULL DEFAULT(0),
	[MagicR] [tinyint] NOT NULL DEFAULT(0),
	[DiseaseR] [tinyint] NOT NULL DEFAULT(0),
	[PoisonR] [tinyint] NOT NULL DEFAULT(0),
	[ExpPct] [tinyint] NOT NULL DEFAULT(0)
)