CREATE TABLE [MAGIC_TYPE6](
	[iNum] [int] NOT NULL,
	[Size] [smallint] NOT NULL DEFAULT(0),
	[TransformID] [smallint] NOT NULL DEFAULT(0),
	[Duration] [smallint] NOT NULL DEFAULT(0),
	[MaxHp] [smallint] NOT NULL DEFAULT(0),
	[MaxMp] [smallint] NOT NULL DEFAULT(0),
	[Speed] [tinyint] NOT NULL DEFAULT(0),
	[AttackSpeed] [smallint] NOT NULL DEFAULT(0),
	[TotalHit] [smallint] NOT NULL DEFAULT(0),
	[TotalAc] [smallint] NOT NULL DEFAULT(0),
	[TotalHitRate] [smallint] NOT NULL DEFAULT(0),
	[TotalEvasionRate] [smallint] NOT NULL DEFAULT(0),
	[TotalFireR] [smallint] NOT NULL DEFAULT(0),
	[TotalColdR] [smallint] NOT NULL DEFAULT(0),
	[TotalLightningR] [smallint] NOT NULL DEFAULT(0),
	[TotalMagicR] [smallint] NOT NULL DEFAULT(0),
	[TotalDiseaseR] [smallint] NOT NULL DEFAULT(0),
	[TotalPoisonR] [smallint] NOT NULL DEFAULT(0),
	[Class] [smallint] NOT NULL DEFAULT(0),
	[UserSkillUse] [tinyint] NOT NULL DEFAULT(0),
	[NeedItem] [tinyint] NOT NULL DEFAULT(0),
	[SkillSuccessRate] [tinyint] NOT NULL DEFAULT(0),
	[MonsterFriendly] [tinyint] NOT NULL DEFAULT(0),
	[Nation] [tinyint] NOT NULL DEFAULT(0)
)
