CREATE TABLE [MAKE_ITEM_GROUP](
	[iItemGroupNum] [int] NOT NULL,
	[iItem_1] [int] NOT NULL DEFAULT(0),
	[iItem_2] [int] NOT NULL DEFAULT(0),
	[iItem_3] [int] NOT NULL DEFAULT(0),
	[iItem_4] [int] NOT NULL DEFAULT(0),
	[iItem_5] [int] NOT NULL DEFAULT(0),
	[iItem_6] [int] NOT NULL DEFAULT(0),
	[iItem_7] [int] NOT NULL DEFAULT(0),
	[iItem_8] [int] NOT NULL DEFAULT(0),
	[iItem_9] [int] NOT NULL DEFAULT(0),
	[iItem_10] [int] NOT NULL DEFAULT(0),
	[iItem_11] [int] NOT NULL DEFAULT(0),
	[iItem_12] [int] NOT NULL DEFAULT(0),
	[iItem_13] [int] NOT NULL DEFAULT(0),
	[iItem_14] [int] NOT NULL DEFAULT(0),
	[iItem_15] [int] NOT NULL DEFAULT(0),
	[iItem_16] [int] NOT NULL DEFAULT(0),
	[iItem_17] [int] NOT NULL DEFAULT(0),
	[iItem_18] [int] NOT NULL DEFAULT(0),
	[iItem_19] [int] NOT NULL DEFAULT(0),
	[iItem_20] [int] NOT NULL DEFAULT(0),
	[iItem_21] [int] NOT NULL DEFAULT(0),
	[iItem_22] [int] NOT NULL DEFAULT(0),
	[iItem_23] [int] NOT NULL DEFAULT(0),
	[iItem_24] [int] NOT NULL DEFAULT(0),
	[iItem_25] [int] NOT NULL DEFAULT(0),
	[iItem_26] [int] NOT NULL DEFAULT(0),
	[iItem_27] [int] NOT NULL DEFAULT(0),
	[iItem_28] [int] NOT NULL DEFAULT(0),
	[iItem_29] [int] NOT NULL DEFAULT(0),
	[iItem_30] [int] NOT NULL DEFAULT(0)
) 