CREATE TABLE [USER_SAVED_MAGIC](
	[strCharID] [varchar](21) NOT NULL,
	[nSkill1] [int] NOT NULL DEFAULT(0),
	[nDuring1] [smallint] NOT NULL DEFAULT(0),
	[nSkill2] [int] NOT NULL DEFAULT(0),
	[nDuring2] [smallint] NOT NULL DEFAULT(0),
	[nSkill3] [int] NOT NULL DEFAULT(0),
	[nDuring3] [smallint] NOT NULL DEFAULT(0),
	[nSkill4] [int] NOT NULL DEFAULT(0),
	[nDuring4] [smallint] NOT NULL DEFAULT(0),
	[nSkill5] [int] NOT NULL DEFAULT(0),
	[nDuring5] [smallint] NOT NULL DEFAULT(0),
	[nSkill6] [int] NOT NULL DEFAULT(0),
	[nDuring6] [smallint] NOT NULL DEFAULT(0),
	[nSkill7] [int] NOT NULL DEFAULT(0),
	[nDuring7] [smallint] NOT NULL DEFAULT(0),
	[nSkill8] [int] NOT NULL DEFAULT(0),
	[nDuring8] [smallint] NOT NULL DEFAULT(0),
	[nSkill9] [int] NOT NULL DEFAULT(0),
	[nDuring9] [smallint] NOT NULL DEFAULT(0),
	[nSkill10] [int] NOT NULL DEFAULT(0),
	[nDuring10] [smallint] NOT NULL DEFAULT(0)
)